### ISSUE TITLE
music: songs are sometimes skipped

### ISSUE THREAD

**Issue by ghost** [taiyaeix/nanobot#13]
When playing a series of songs, sometimes a song is skipped, and _usually_ the remaining songs in the queue are played for only a couple seconds then skipped as well. Sometimes, only a couple are skipped.

**Comment by taiyaeix** [comment]
Easy solution to this is to just download the song and then start an ffmpeg stream to the file when playing the song instead of running a connection to YT.

**Comment by taiyaeix** [comment]
Closed by 0b7f06e877dfb857c474c68351ff956a47612fc9.
