### ISSUE TITLE
tags: add alias command

### ISSUE THREAD

**Issue by ghost** [taiyaeix/nanobot#18]
Tags are sometimes rememberable by two or more names, rather than just one. Rather than having, say, 3 tags with the same value, an alias should be created, so that each alias reflects the value of the original tag.

e.g.:

A tag set via `? best animal: cats`

If someone is very contrarian, they might want to create an alias:

`? alias best animal --> worst animal` or `? alias best animal: worst animal`

Which will create an alias named `worst animal`, which will _always_ reflect the value of `best animal`. If `best animal` is updated, `worst animal` will reflect the value.

When renaming the original tag, the alias will point to the new tag.

When deleting the original tag, a warning will be posted _if_ is at least one alias, asking if the user is sure they want to delete the tag, including all aliases. If they say yes, then all aliases pointing to that tag will also be deleted.

**Comment by zeylasjelkov** [comment]
Blocked by #8.

**Comment by taiyaeix** [comment]
I've decided against this, as tags are otherwise simple, and should not be complicated.
