### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by ghost** [taiyaeix/nanobot#25]
The project is horribly structured right now.

- `help` should be in its own command, rather than in the `on_message` event
- tags should be in their own module
- stop using discord.py's command extension system

**Comment by zeylasjelkov** [comment]
Additionally, refactor all of the commands. Many of them were just tacked on.

**Comment by zeylasjelkov** [comment]
Blocked by #8 and possibly #7 depending on the Rust bins' setups.

**Comment by taiyaeix** [comment]
Blockers are closed.
